# controller_manager_ns: controller_manager

controller_list:
  - name: /frrobot/position_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - fr3_j1
      - fr3_j2
      - fr3_j3
      - fr3_j4
      - fr3_j5
      - fr3_j6
initial:  # Define initial robot poses.
  - group: fr3v6_arm
    pose: zero
