# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fr3v6_arm
  joint_model_group_pose: zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - fr3_j1
    - fr3_j2
    - fr3_j3
    - fr3_j4
    - fr3_j5
    - fr3_j6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - fr3_j1
      - fr3_j2
      - fr3_j3
      - fr3_j4
      - fr3_j5
      - fr3_j6
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - fr3_j1
    - fr3_j2
    - fr3_j3
    - fr3_j4
    - fr3_j5
    - fr3_j6
  gains:
    fr3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1